plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ru.alltime'
version = '0.0.1-SNAPSHOT'
description = 'dogovora-alltime'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'          // можно оставить
    implementation 'org.springframework.boot:spring-boot-starter-web'      // <— нужен для сервера (Tomcat)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    // Swagger UI (у тебя уже есть springdoc.* в properties)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.13'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
