services:
  alltimeDb:
    #TODO написать в чате "рекомендуется сделать docker rm -f dogovora-postgres (старое название)"
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dogovora-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com #это вставлять в логин
      PGADMIN_DEFAULT_PASSWORD: admin #это в пароль # Эти два поля не нужны
      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./${POSTGRES_DB}/pgadmin:/var/lib/pgadmin
#TODO также я должен расписать туториал что делать и что регистрировать
#спросить у чата гпт откуда он взял данные для заполнения (alltime и прочие!)
    ports:
      - "5050:80" #TODO вставить переменную (надо ли)
    networks:
      - dogovora-network
    depends_on:
      - alltimeDb
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  dogovora-network:
    driver: bridge
