spring.datasource.url=jdbc:postgresql://localhost:5432/dogovora_db
spring.datasource.username=alltime
spring.datasource.password=alltime
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.main.web-application-type=servlet
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html