spring.datasource.url=jdbc:postgresql://localhost:5432/dogovora_db
spring.datasource.username=alltime
spring.datasource.password=alltime
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.main.web-application-type=servlet
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html