spring.datasource.url=jdbc:postgresql://localhost:5432/dogovora_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.main.web-application-type=servlet
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html