name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Show system info
        run: |
          echo "USER: $(whoami)"
          echo "HOST: $(hostname)"
          echo "PWD: $(pwd)"
          uname -a
